const LANG = {
  en: {
    app: "Food Cost",
    welcome: "Welcome to the Food Cost",
    tagline: "Quickly and easily calculate the actual amount you paid for food.",
    start: "calculate",
    theBill: "The Bill:",
    comingSoon: "Coming soon...",
    settings: "Settings",
    theme: "Theme",
    language: "Language",
    years: "Years",
    weight: "Weight (kg)",
    chart: "CHART?",
    footer: "Food Cost © 2026",
    developed: "Developed by Lyuben Kikov - all rights reserved ;/",
    reset: "reset",

    
    group: "Group",
    dailyCalories: "Daily Calories",
    watts: "Watts",
    women: "Women",
    men: "Men",
    children: "Children (2–18)",
    average: "Average",
    kcalWomen: "1600 – 2400 kcal",
    kcalMen: "2200 – 3000+ kcal",
    kcalChildren: "1000 – 3200 kcal",
    kcalAverage: "2600 kcal",
    wWomen: "77 – 116 W",
    wMen: "106 – 145+ W",
    wChildren: "48 – 155 W",
    wAverage: "126 W",
    flip: "flip",
    back: "back"
  },

  bg: {
    app: "Цената на Храната",
    welcome: "Добре дошли в Цената на Храната",
    tagline: "Изчислете бързо и лесно реалната сума, която сте платили за изхранване.",
    start: "калкулирай",
    theBill: "Сметката:",
    comingSoon: "Очаквайте скоро...",
    settings: "Настройки",
    theme: "Тема",
    language: "Език",
    years: "Години",
    weight: "Тегло (кг)",
    chart: "диаграма?",
    footer: "Цената на Храната © 2026",
    developed: "разработено от Любен Киков - всички права запазени ;/",
    reset: "изчисти",

    
    
    group: "Група",
    dailyCalories: "Дневни калории",
    watts: "Ватове",
    women: "Жени",
    men: "Мъже",
    children: "Деца (2–18)",
    average: "Средно",
    kcalWomen: "1600 – 2400 kcal",
    kcalMen: "2200 – 3000+ kcal",
    kcalChildren: "1000 – 3200 kcal",
    kcalAverage: "2600 kcal",
    wWomen: "77 – 116 W",
    wMen: "106 – 145+ W",
    wChildren: "48 – 155 W",
    wAverage: "126 W",
    flip: "виж още",
    back: "обратно"
  }
};
